language: node_js

node_js:
  - "node"

services:
  - redis-server

cache:
  yarn : true
  directories:
    - "node_modules"

branches:
  except:
    # do not build any branches that have *.tmp in their name
    - /.*\.tmp$/

after_success: yarn run coverage
